'use client';
import { Html, OrbitControls, RoundedBox } from '@react-three/drei';
import { useMemo, useState } from 'react';
import { useSnapshot } from 'valtio';
import { setupViewerState } from './store';
import type { GripType, ViewerLabels } from './types';
type Inspector = { title: string; rows: Array<[string, string]> } | null;
interface Props { labels: ViewerLabels; gripType: GripType; palmContactRatio: number; movementAmplitude: number; }
const keyboardRows: Record<string, number[]> = { '60%':[14,14,14,13], '65%':[14,14,14,13], '75%':[15,15,15,14], TKL:[15,15,15,14,4], full:[16,16,16,15,4] };
function Desk(){return <group><RoundedBox args={[11,.45,5.5]} radius={.14} smoothness={4} position={[0,-.25,0]}><meshStandardMaterial color="#111827" roughness={.62} metalness={.18}/></RoundedBox>{[[-4.8,-1.8,-2.1],[4.8,-1.8,-2.1],[-4.8,-1.8,2.1],[4.8,-1.8,2.1]].map((p,i)=><mesh key={i} position={p as [number,number,number]}><boxGeometry args={[.35,3.1,.35]}/><meshStandardMaterial color="#0b1220"/></mesh>)}</group>}
function Monitor({aspect,refresh,labels,onInspect}:{aspect:number;refresh:number;labels:ViewerLabels;onInspect:(x:Inspector)=>void}){const width=3.1,height=width/aspect;return <group position={[0,1.35,-1.75]} onClick={e=>{e.stopPropagation();onInspect({title:labels.monitor,rows:[[labels.refreshRate,`${refresh} Hz`],[labels.aspectRatio,`${aspect.toFixed(2)}:1`]]})}}><RoundedBox args={[width,height,.12]} radius={.08} smoothness={3}><meshStandardMaterial color="#05070b" roughness={.2} metalness={.75}/></RoundedBox><mesh position={[0,0,.07]}><planeGeometry args={[width-.16,height-.16]}/><meshStandardMaterial color="#0f172a" emissive="#071a2e" emissiveIntensity={.35}/></mesh><mesh position={[0,-height/2-.55,0]}><boxGeometry args={[.16,1.05,.16]}/><meshStandardMaterial color="#111827" metalness={.6}/></mesh><mesh position={[0,-height-.08,0]}><boxGeometry args={[1.55,.08,.72]}/><meshStandardMaterial color="#111827" metalness={.55}/></mesh><Html position={[width/2-.25,height/2-.2,.15]} center><span style={{color:'#a7f3d0',font:'600 11px ui-monospace',whiteSpace:'nowrap'}}>{refresh} Hz</span></Html></group>}
function Keyboard({layout,labels,onInspect}:{layout:keyof typeof keyboardRows;labels:ViewerLabels;onInspect:(x:Inspector)=>void}){const rows=keyboardRows[layout],keyW=layout==='full'?.18:.2;return <group position={[-2.25,.15,.75]} rotation={[-.035,0,0]} onClick={e=>{e.stopPropagation();onInspect({title:labels.keyboard,rows:[[labels.keyboard,layout],[labels.actuation,'0.1–4.0 mm']]})}}><RoundedBox args={[3.65,.18,1.45]} radius={.08} smoothness={3}><meshStandardMaterial color="#090d15" roughness={.5} metalness={.35}/></RoundedBox>{rows.map((count,row)=>{const total=count*keyW+(count-1)*.035;return Array.from({length:count},(_,col)=><mesh key={`${row}-${col}`} position={[-total/2+col*(keyW+.035)+keyW/2,.12,-.5+row*.25]}><boxGeometry args={[keyW,.055,.18]}/><meshStandardMaterial color="#1f2937" roughness={.48}/></mesh>)})}</group>}
function Mousepad({surface,movementAmplitude,labels,onInspect}:{surface:'speed'|'control';movementAmplitude:number;labels:ViewerLabels;onInspect:(x:Inspector)=>void}){const opacity=surface==='speed'?.82:.92,range=Math.max(.7,Math.min(2.4,movementAmplitude/100));return <group position={[2.15,.05,.78]} onClick={e=>{e.stopPropagation();onInspect({title:labels.mousepad,rows:[[labels.mousepad,surface==='speed'?labels.speed:labels.control],[labels.movementRange,`${movementAmplitude.toFixed(0)}%`]]})}}><RoundedBox args={[4.2,.06,2.25]} radius={.1} smoothness={3}><meshStandardMaterial color={surface==='speed'?'#18202d':'#151a24'} roughness={surface==='speed'?.3:.72} transparent opacity={opacity}/></RoundedBox><mesh position={[0,.05,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.2*range,.23*range,48]}/><meshBasicMaterial color="#34d399" transparent opacity={.8}/></mesh><mesh position={[0,.055,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.85*range,.87*range,64]}/><meshBasicMaterial color="#34d399" transparent opacity={.24}/></mesh></group>}
function Mouse({model,gripType,palmContactRatio,labels,onInspect}:{model:string;gripType:GripType;palmContactRatio:number;labels:ViewerLabels;onInspect:(x:Inspector)=>void}){const heat=Math.max(0,Math.min(1,palmContactRatio));const points=useMemo(()=>[[-.24,.18,.08],[0,.23,.1],[.24,.18,.08],[0,-.1,.11]] as [number,number,number][],[]);const dims=model==='lightweight-mouse'?[.92,.34,1.55]:model==='ergo-mouse'?[1.16,.43,1.62]:[1.05,.38,1.7];return <group position={[2.1,.22,.78]} rotation={[0,-.18,0]} onClick={e=>{e.stopPropagation();onInspect({title:labels.mouse,rows:[[labels.gripHeatmap,gripType],[labels.mouse,`${Math.round(heat*100)}%`],[labels.dpi,'800'],[labels.latency,'< 1 ms']]})}}><RoundedBox args={dims as [number,number,number]} radius={.25} smoothness={6}><meshStandardMaterial color="#202938" roughness={.28} metalness={.3}/></RoundedBox><mesh position={[0,dims[1]/2+.01,.22]}><boxGeometry args={[.025,.035,.58]}/><meshStandardMaterial color="#334155"/></mesh>{points.map(([x,y,z],i)=><mesh key={i} position={[x,y,z]}><sphereGeometry args={[.14+heat*.05,20,12]}/><meshBasicMaterial color="#ef4444" transparent opacity={.18+heat*.3} depthWrite={false}/></mesh>)}</group>}
export function SetupScene({labels,gripType,palmContactRatio,movementAmplitude}:Props){const state=useSnapshot(setupViewerState);const [inspector,setInspector]=useState<Inspector>(null);return <><color attach="background" args={['#070b12']}/><ambientLight intensity={1.5}/><directionalLight position={[4,7,3]} intensity={3.2} castShadow/><pointLight position={[-4,3,-2]} intensity={18} distance={12} color="#22c55e"/><Desk/><Monitor aspect={Number(state.monitorAspectRatio)} refresh={Number(state.monitorRefreshRate)} labels={labels} onInspect={setInspector}/><Keyboard layout={state.keyboardLayout as keyof typeof keyboardRows} labels={labels} onInspect={setInspector}/><Mousepad surface={state.mousepadSurface} movementAmplitude={movementAmplitude} labels={labels} onInspect={setInspector}/><Mouse model={String(state.mouseModel)} gripType={gripType} palmContactRatio={palmContactRatio} labels={labels} onInspect={setInspector}/><OrbitControls makeDefault enableDamping dampingFactor={.08} minDistance={5.5} maxDistance={15} target={[0,.25,0]}/><Html position={[0,4,0]} center><div style={{color:'#94a3b8',font:'600 12px ui-monospace',letterSpacing:'.12em',textTransform:'uppercase',pointerEvents:'none'}}>{labels.title}</div></Html>{inspector&&<Html position={[0,1.5,2.7]} center distanceFactor={7}><div style={{width:220,padding:14,borderRadius:12,border:'1px solid rgba(148,163,184,.18)',background:'rgba(2,6,23,.94)',boxShadow:'0 20px 60px rgba(0,0,0,.45)',color:'#e2e8f0',fontFamily:'ui-sans-serif'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,marginBottom:10}}><strong>{inspector.title}</strong><button type="button" aria-label={labels.close} onClick={()=>setInspector(null)} style={{color:'#94a3b8',background:'none',border:0,cursor:'pointer'}}>×</button></div>{inspector.rows.map(([key,value])=><div key={key} style={{display:'flex',justifyContent:'space-between',gap:10,padding:'5px 0',fontSize:12}}><span style={{color:'#64748b'}}>{key}</span><span>{value}</span></div>)}</div></Html>}</>}
